apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metada: 
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gustavos_andrade@hotmail.com
    privateKeySecretRef:
      name: letsencrypt-lts
    solvers:
    - http01:
        ingress:
          class: nginx
